"""
Django settings for jewel_finance project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from datetime import timedelta
from importlib.util import find_spec
from pathlib import Path
from urllib.parse import urlparse

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# --- RENDER SPECIFIC CONFIGURATION ---
RENDER_SERVICE_ID = os.getenv("RENDER_SERVICE_ID", "srv-d7lhl257vvec73b9tj3g")
# Your Live Site Link
RENDER_EXTERNAL_URL = os.getenv(
    "RENDER_EXTERNAL_URL",
    "https://fianance-management-system-erp.onrender.com",
).strip()
IS_ON_RENDER = "RENDER" in os.environ

def load_env_file(file_path):
    if not file_path.exists():
        return

    for raw_line in file_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()

        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")

        if key:
            os.environ.setdefault(key, value)


load_env_file(BASE_DIR / ".env")
load_env_file(BASE_DIR.parent / ".env")


def env_bool(name, default=False):
    value = os.getenv(name)

    if value is None:
        return default

    normalized = value.strip().lower()

    if normalized in {"1", "true", "yes", "on"}:
        return True

    if normalized in {"0", "false", "no", "off"}:
        return False

    return default


def env_int(name, default):
    value = os.getenv(name)

    if value is None:
        return default

    try:
        return int(value.strip())
    except ValueError as error:
        raise ImproperlyConfigured(f"{name} must be a valid integer.") from error


def env_list(name, default=""):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


def build_csv_default(*values):
    unique_values = []

    for value in values:
        normalized_value = str(value or "").strip()

        if normalized_value and normalized_value not in unique_values:
            unique_values.append(normalized_value)

    return ",".join(unique_values)


RUNNING_TESTS = "test" in sys.argv
LOCAL_DEVELOPMENT_COMMANDS = {"runserver", "shell", "migrate", "makemigrations", "createsuperuser"}
ALLOW_LOCAL_DEFAULTS = RUNNING_TESTS or any(command in sys.argv for command in LOCAL_DEVELOPMENT_COMMANDS)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY") or os.getenv("Tharun")

if not SECRET_KEY:
    if ALLOW_LOCAL_DEFAULTS:
        SECRET_KEY = "django-insecure-development-only-secret-key"
    else:
        raise ImproperlyConfigured(
            "SECRET_KEY must be set in the environment before starting the backend."
        )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", ALLOW_LOCAL_DEFAULTS)

render_external_host = urlparse(RENDER_EXTERNAL_URL).hostname if RENDER_EXTERNAL_URL else ""
render_external_origin = ""

if RENDER_EXTERNAL_URL:
    parsed_render_url = urlparse(RENDER_EXTERNAL_URL)

    if parsed_render_url.scheme and parsed_render_url.netloc:
        render_external_origin = f"{parsed_render_url.scheme}://{parsed_render_url.netloc}"

ALLOWED_HOSTS = env_list(
    "ALLOWED_HOSTS",
    build_csv_default("127.0.0.1", "localhost", "testserver", render_external_host),
)
CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
    build_csv_default(
        "http://127.0.0.1:3000",
        "http://localhost:3000",
        render_external_origin,
    ),
)
JWT_PACKAGE_AVAILABLE = find_spec("rest_framework_simplejwt") is not None
ENABLE_JWT_AUTH = env_bool("ENABLE_JWT_AUTH", JWT_PACKAGE_AVAILABLE)

if ENABLE_JWT_AUTH and not JWT_PACKAGE_AVAILABLE:
    raise ImproperlyConfigured(
        "ENABLE_JWT_AUTH is enabled, but djangorestframework-simplejwt is not installed."
    )

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'ledger',
]

if ENABLE_JWT_AUTH:
    INSTALLED_APPS.append('rest_framework_simplejwt.token_blacklist')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jewel_finance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jewel_finance.wsgi.application'
ASGI_APPLICATION = 'jewel_finance.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_ENGINE = os.getenv("DB_ENGINE", "sqlite").strip().lower()

if DB_ENGINE == "mysql":
    required_database_env_vars = ["DB_NAME", "DB_USER", "DB_PASSWORD"]
    missing_database_env_vars = [
        env_var_name
        for env_var_name in required_database_env_vars
        if not os.getenv(env_var_name, "").strip()
    ]

    if missing_database_env_vars:
        missing_env_var_list = ", ".join(sorted(missing_database_env_vars))
        raise ImproperlyConfigured(
            f"MySQL configuration requires the following environment variables: {missing_env_var_list}."
        )

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.getenv("DB_NAME", "").strip(),
            "USER": os.getenv("DB_USER", "").strip(),
            "PASSWORD": os.getenv("DB_PASSWORD", "").strip(),
            "HOST": os.getenv("DB_HOST", "127.0.0.1"),
            "PORT": os.getenv("DB_PORT", "3306"),
            "OPTIONS": {
                "charset": "utf8mb4",
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 10,
        },
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

SESSION_COOKIE_NAME = "jewel_finance_session"
SESSION_COOKIE_AGE = env_int("SESSION_COOKIE_AGE", 60 * 60 * 8)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = os.getenv("SESSION_COOKIE_SAMESITE", "Lax")
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", not DEBUG)

CSRF_COOKIE_NAME = "jewel_finance_csrf"
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = os.getenv("CSRF_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", not DEBUG)

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", not DEBUG)
SECURE_HSTS_SECONDS = env_int("SECURE_HSTS_SECONDS", 0 if DEBUG else 31536000)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS",
    not DEBUG,
)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = os.getenv(
    "SECURE_REFERRER_POLICY",
    "strict-origin-when-cross-origin",
)
SECURE_CROSS_ORIGIN_OPENER_POLICY = os.getenv(
    "SECURE_CROSS_ORIGIN_OPENER_POLICY",
    "same-origin",
)
X_FRAME_OPTIONS = "DENY"

LOGIN_RATE_LIMIT_ATTEMPTS = env_int("LOGIN_RATE_LIMIT_ATTEMPTS", 5)
LOGIN_RATE_LIMIT_WINDOW_SECONDS = env_int("LOGIN_RATE_LIMIT_WINDOW_SECONDS", 300)

rest_framework_authentication_classes = [
    'rest_framework.authentication.SessionAuthentication',
]

if ENABLE_JWT_AUTH:
    rest_framework_authentication_classes.append(
        'rest_framework_simplejwt.authentication.JWTAuthentication'
    )

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': rest_framework_authentication_classes,
}

if ENABLE_JWT_AUTH:
    SIMPLE_JWT = {
        'ACCESS_TOKEN_LIFETIME': timedelta(
            minutes=env_int("JWT_ACCESS_TOKEN_LIFETIME_MINUTES", 30)
        ),
        'REFRESH_TOKEN_LIFETIME': timedelta(
            days=env_int("JWT_REFRESH_TOKEN_LIFETIME_DAYS", 7)
        ),
        'ROTATE_REFRESH_TOKENS': True,
        'BLACKLIST_AFTER_ROTATION': True,
        'UPDATE_LAST_LOGIN': True,
        'AUTH_HEADER_TYPES': ('Bearer',),
        'SIGNING_KEY': SECRET_KEY,
    }

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
