# Generated by Django 6.0.3 on 2026-03-21 11:17

import django.core.validators
import ledger.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0002_seed_tharun_login_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('father_or_husband_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('age', models.PositiveSmallIntegerField()),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile number must be a valid 10-digit Indian number.', regex='^[6-9]\\d{9}$')])),
                ('occupation', models.CharField(max_length=120)),
                ('identity_proof_type', models.CharField(choices=[('aadhaar_card', 'Aadhaar Card'), ('voter_id', 'Voter ID'), ('driving_license', 'Driving License'), ('passport', 'Passport')], max_length=20)),
                ('identity_proof_name', models.CharField(max_length=150)),
                ('identity_proof_number', models.CharField(max_length=50)),
                ('identity_proof_file', models.FileField(upload_to='customers/identity/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'])])),
                ('address_proof_type', models.CharField(choices=[('aadhaar_voter_id', 'Aadhaar / Voter ID'), ('eb_water_bill', 'EB bill / Water bill'), ('rental_agreement', 'Rental agreement')], max_length=20)),
                ('address_proof_file', models.FileField(upload_to='customers/address/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'])])),
                ('photo', models.FileField(upload_to='customers/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), ledger.models.validate_photo_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
