# Generated by Django 6.0.3 on 2026-03-24 12:08

import django.core.validators
import ledger.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gemstone_carat_or_quantity',
            field=models.CharField(default='N/A', max_length=60),
        ),
        migrations.AddField(
            model_name='customer',
            name='gemstone_type',
            field=models.CharField(default='N/A', max_length=60),
        ),
        migrations.AddField(
            model_name='customer',
            name='hallmark_or_makers_mark',
            field=models.CharField(default='N/A', max_length=120),
        ),
        migrations.AddField(
            model_name='customer',
            name='item_condition',
            field=models.CharField(choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair')], default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='item_type',
            field=models.CharField(choices=[('ring', 'Ring'), ('chain', 'Chain'), ('necklace', 'Necklace'), ('bracelet', 'Bracelet'), ('bangle', 'Bangle'), ('earring', 'Earring'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='jewelry_photo',
            field=models.FileField(default='customers/jewelry/default-jewelry.webp', upload_to='customers/jewelry/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), ledger.models.validate_photo_size]),
        ),
        migrations.AddField(
            model_name='customer',
            name='metal_type',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum'), ('other', 'Other')], default='gold', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='purity_or_karat',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='weight_grams',
            field=models.DecimalField(decimal_places=3, default=0.001, max_digits=8),
        ),
    ]
