# Generated by Django 6.0.3 on 2026-04-09 09:55

import django.core.validators
import ledger.models
from django.db import migrations, models


def seed_workspace_sequences(apps, schema_editor):
    Customer = apps.get_model('ledger', 'Customer')
    WorkspaceSettings = apps.get_model('ledger', 'WorkspaceSettings')

    settings_obj, _ = WorkspaceSettings.objects.get_or_create(
        pk=1,
        defaults={
            'sno_format': 'SNO-{number:04}',
            'ano_format': 'ANO-{number:04}',
            'next_sno_number': 1,
            'next_ano_number': 1,
        },
    )

    customers = Customer.objects.order_by('created_at', 'id')
    next_sno_number = settings_obj.next_sno_number
    next_ano_number = settings_obj.next_ano_number

    for customer in customers:
        update_fields = []

        if not customer.sno:
            customer.sno_sequence = next_sno_number
            customer.sno = ledger.models.render_sequence_value(settings_obj.sno_format, next_sno_number)
            next_sno_number += 1
            update_fields.extend(['sno', 'sno_sequence'])

        if not customer.ano:
            customer.ano_sequence = next_ano_number
            customer.ano = ledger.models.render_sequence_value(settings_obj.ano_format, next_ano_number)
            next_ano_number += 1
            update_fields.extend(['ano', 'ano_sequence'])

        if update_fields:
            customer.save(update_fields=update_fields)

    settings_obj.next_sno_number = next_sno_number
    settings_obj.next_ano_number = next_ano_number
    settings_obj.save(update_fields=['next_sno_number', 'next_ano_number', 'updated_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno_format', models.CharField(default='SNO-{number:04}', max_length=80, validators=[ledger.models.validate_sequence_format])),
                ('ano_format', models.CharField(default='ANO-{number:04}', max_length=80, validators=[ledger.models.validate_sequence_format])),
                ('next_sno_number', models.PositiveIntegerField(default=1)),
                ('next_ano_number', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workspace Settings',
                'verbose_name_plural': 'Workspace Settings',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='ano',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ano_sequence',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='jewel_entries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customer',
            name='sno',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sno_sequence',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_proof_file',
            field=models.FileField(blank=True, null=True, upload_to='customers/address/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_proof_type',
            field=models.CharField(blank=True, choices=[('aadhaar_voter_id', 'Aadhaar / Voter ID'), ('eb_water_bill', 'EB bill / Water bill'), ('rental_agreement', 'Rental agreement')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gemstone_carat_or_quantity',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gemstone_type',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='customer',
            name='hallmark_or_makers_mark',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='customer',
            name='identity_proof_file',
            field=models.FileField(blank=True, null=True, upload_to='customers/identity/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='identity_proof_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='customer',
            name='identity_proof_type',
            field=models.CharField(choices=[('aadhaar_card', 'Aadhaar Card'), ('voter_id', 'Voter ID'), ('driving_license', 'Driving License'), ('passport', 'Passport')], default='aadhaar_card', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='item_condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='item_type',
            field=models.CharField(blank=True, choices=[('ring', 'Ring'), ('chain', 'Chain'), ('necklace', 'Necklace'), ('bracelet', 'Bracelet'), ('bangle', 'Bangle'), ('earring', 'Earring'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='jewelry_photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='customers/jewelry/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), ledger.models.validate_photo_size]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='metal_type',
            field=models.CharField(blank=True, choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile number must be a valid 10-digit Indian number.', regex='^[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='customer',
            name='purity_or_karat',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='weight_grams',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.RunPython(seed_workspace_sequences, migrations.RunPython.noop),
    ]
