# Generated by Django 6.0.3 on 2026-04-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_workspacesettings_customer_ano_customer_ano_sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='number_of_stones',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='identity_proof_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='identity_proof_type',
            field=models.CharField(blank=True, choices=[('aadhaar_card', 'Aadhaar Card'), ('voter_id', 'Voter ID'), ('driving_license', 'Driving License'), ('passport', 'Passport')], default='', max_length=20),
        ),
    ]
