# Generated by Django 6.0.3 on 2026-04-10 16:25

import django.core.validators
import ledger.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_customer_address_customer_number_of_stones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='customers/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), ledger.models.validate_photo_size]),
        ),
    ]
